bachya/aionotion

- .coveragerc
- .gitignore
- AUTHORS.md
- Makefile
- Pipfile
- README.md
- aionotion/__init__.py
- aionotion/const.py
- aionotion/errors.py
- example.py
- pylintrc
- setup.py
- tests/__init__.py
- tests/const.py
- tests/fixtures/api.py
- tests/test_api.py
- tox.ini
This PR creates the first official release of the library.
N/A
**Checklist:**
> Commit initial library

- README.md
- aionotion/client.py
- aionotion/device.py
- tests/fixtures/device.py
- tests/test_device.py
This PR adds endpoints for dealing with devices.
N/A
**Checklist:**
> Create device endpoints

- README.md
- aionotion/system.py
- tests/fixtures/system.py
- tests/test_system.py
This PR adds all remaining endpoints for systems (i.e., accounts).
N/A
**Checklist:**
> Add remaining system endpoints

- README.md
- aionotion/sensor.py
- tests/fixtures/sensor.py
- tests/test_sensor.py
This PR adds all remaining endpoints for sensors.
N/A
**Checklist:**
> Add remaining sensor endpoints

- README.md
- aionotion/task.py
- tests/fixtures/task.py
- tests/test_task.py
This PR adds all remaining endpoints for tasks.
N/A
**Checklist:**
> Add remaining task endpoints

- aionotion/client.py
- aionotion/errors.py
- tests/fixtures/__init__.py
- tests/test_client.py
This PR introduces a specific exception for invalid credentials.
N/A
**Checklist:**
> Add specific exception for invalid credentials

- aionotion/client.py
This PR performs some gentle code cleanup.
N/A
**Checklist:**
> Perform some code cleanup

- .github/release-drafter.yml
- pyproject.toml
This PR makes a few changes to the Release Drafter configuration:
1. Adds a `breaking change` configuration
2. Adds a `maintenance` configuration
N/A
**Checklist:**
> Update release drafter configuration (breaking changes, maintenance)

- tests/fixtures/task_all_response.json
- tests/test_task.py
Notion recently changed their tasks API response payload; this PR adjusts the fixtures and tests to reflect this.
N/A
**Checklist:**
> Update tasks tests and fixtures for new API response payload

- README.md
- pyproject.toml
This PR makes Python 3.7 the minimum supported version.
N/A
**Checklist:**
> Make Python 3.7 the minimum supported version

- .github/workflows/ci.yaml
- README.md
- noxfile.py
- pyproject.toml
- requirements_test.txt
This PR introduces [`nox`](https://github.com/wntrblm/nox) for test automation.
Fixes https://github.com/bachya/aioguardian/issues/<ISSUE ID>
**Checklist:**
> Use nox for test automation

- .rtx.toml
> Add an `rtx` config file

- aionotion/client.py
> Slightly adjust debug log for received data

- aionotion/sensor/models.py
> Add additional listener types

- aionotion/sensor/models.py
> Only log a warning when finding an unknown listener kind

- aionotion/bridge/__init__.py
- aionotion/client.py
- aionotion/device/__init__.py
- aionotion/sensor/__init__.py
- aionotion/system/__init__.py
- tests/test_client.py
SSIA. This allows us to type things more nicely.
N/A
**Checklist:**
> Pass `Client` object to all endpoint management objects

- README.md
- aionotion/client.py
- aionotion/user/__init__.py
- aionotion/user/models.py
- tests/fixtures/user_preferences_response.json
- tests/test_user.py
This provides a new API call:
- `client.user.async_preferences()`: get user preferences
N/A
**Checklist:**
> Add `user` endpoint

- README.md
- aionotion/bridge/__init__.py
- aionotion/device/__init__.py
- aionotion/sensor/__init__.py
- aionotion/system/__init__.py
- aionotion/user/__init__.py
- tests/test_bridge.py
- tests/test_device.py
- tests/test_sensor.py
- tests/test_system.py
- tests/test_user.py
It turns out its easier to type results by including the entire response, so let's do that. It does mean that implementers will need to update.
N/A
**Checklist:**
> Return Pydantic models that encompass the entire response

- aionotion/bridge/models.py
- tests/fixtures/bridge_all_response.json
- tests/test_bridge.py
Surfaced by a Home Assistant user: https://github.com/home-assistant/core/issues/93292
N/A
**Checklist:**
> Fix another model validation error re: firmware version

- poetry.lock
- pyproject.toml
SSIA
Fixes https://github.com/bachya/aionotion/security/dependabot/5
Fixes https://github.com/bachya/aionotion/security/dependabot/6
**Checklist:**
> Pin `certifi` and `Pygments` versions to fix CVEs

- aionotion/client.py
- tests/test_client.py
> Define a `refresh_token` client property

- aionotion/client.py
- tests/test_client.py
If multiple concurrent calls were executing when the access token needed refreshing, they wouldn't wait for one another; that race condition would lead to the other calls raising an `InvalidCredentialsError` error. This PR ensures that if any call starts refresh cycle, other calls wait until it has completed.
N/A
**Checklist:**
> Fix issue with concurrent calls while refreshing an access token

- aionotion/listener/models.py
- tests/fixtures/sensor_listeners_response.json
- tests/test_listener.py
SSIA. This allows us to represent a listener's type without a separate call.
N/A
**Checklist:**
-  [x] Confirm that one or more new tests are written for the new functionality.
> feat: add listener kind as an attribute to each `Listener`
